from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from m import MainWindowMinerals


class StartMenu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1261, 841)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-20, -10, 1261, 841))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../Users/maria/Downloads/mnrl.FmiML.jpg"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(500, 220, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Felix Titling")
        font.setPointSize(32)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setLineWidth(20)
        self.label_5.setMidLineWidth(20)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(310, 310, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Centaur")
        font.setPointSize(25)
        self.label_6.setFont(font)
        self.label_6.setLineWidth(20)
        self.label_6.setMidLineWidth(20)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 310, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Centaur")
        font.setPointSize(25)
        self.label_7.setFont(font)
        self.label_7.setLineWidth(20)
        self.label_7.setMidLineWidth(20)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 520, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Centaur")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(200, 177, 178);\n"
                                        "border: 2px ;\n"
                                        "border-radius: 5px;\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(630, 310, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Centaur")
        font.setPointSize(25)
        self.label_8.setFont(font)
        self.label_8.setLineWidth(20)
        self.label_8.setMidLineWidth(20)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(920, 310, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Centaur")
        font.setPointSize(25)
        self.label_9.setFont(font)
        self.label_9.setLineWidth(20)
        self.label_9.setMidLineWidth(20)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(False)
        self.label_9.setObjectName("label_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 390, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Centaur")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(200, 177, 178);\n"
                                        "border: 2px ;\n"
                                        "border-radius: 5px;\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(360, 390, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Centaur")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(200, 177, 178);\n"
                                        "border: 2px ;\n"
                                        "border-radius: 5px;\n"
                                        "}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(670, 390, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Centaur")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(200, 177, 178);\n"
                                        "border: 2px ;\n"
                                        "border-radius: 5px;\n"
                                        "}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(970, 390, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Centaur")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(200, 177, 178);\n"
                                        "border: 2px ;\n"
                                        "border-radius: 5px;\n"
                                        "}")
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1261, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Classes"))
        self.label_6.setText(_translate("MainWindow", "Classification"))
        self.label_7.setText(_translate("MainWindow", "Minerals"))
        self.pushButton_2.setText(_translate("MainWindow", "Add new class"))
        self.label_8.setText(_translate("MainWindow", "Features"))
        self.label_9.setText(_translate("MainWindow", "Field of usage"))
        self.pushButton_3.setText(_translate("MainWindow", "View instances"))
        self.pushButton_7.setText(_translate("MainWindow", "View instances"))
        self.pushButton_4.setText(_translate("MainWindow", "View instances"))
        self.pushButton_5.setText(_translate("MainWindow", "View instances"))

# def showStartMenu():
#     MainWindow = QtWidgets.QMainWindow()
#     ui = StartMenu()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
